---
title: "Supplementary"
author: "Sofie McComb"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## VIF Tables
Make table with VIFs or maybe a correlation plot (library = corrplot) for the landscape and patch metrics (Percent crop, edge density crops, mean patch size crops, large farms, crop diversity, landscape diversity) for final best model. 

## Conley Standard Errors
Perform Conley standard errors using best model on centroids of counties (200 km, no time lags) to examine spatial autocorrelation on final best model, without regional effects (http://www.trfetzer.com/using-r-to-estimate-spatial-hac-errors-per-conley/)


## Robustness Check: <1% Cropland
Remove counties with <1% of cropland (NLCD) and run best model, reporting in supplementary section on how many observations it removes; create map showing which counties are removed


## Robustness Check: Percent Crop (NLCD) vs Harvested Crop (CoA)
Replaced percent crop (NLCD) with harvested crop (CoA) and re-run best model to identify if results change

## Robustness Check: Fixed Effects County vs ASD
Run best model with fixed effects on county instead of ASD for supplementary figure, including table of xtsum output showing ASD better than county level in terms of remaining variation

## CoA only cross-sectional models
Retrive CoA data back to 1987 and create boxplots and run cross-sectional models on CoA data (large farm, crop covariates, harvested crop) from 1987-2017


 
